site_name: Notes of gezq0601
nav:
  - Home: index.md
  - Software: 
    - Typora: software/typora.md
    - Git: software/git.md
  - CAGD: 
    - Pre-school Tasks: cagd/pre-school_tasks.md
    - Course Tasks: cagd/course_tasks.md
    - Barycentric Coordinates: cagd/barycentric_coordinates.md
  - Cpp:
    - libigl: cpp/libigl.md
  - Python:
    - numpy: python/numpy.md
  - About: about.md
# theme: readable

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js